import React, { useCallback, useEffect, useRef, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:5000/api';

const CONTRACT_PANEL_CACHE_KEY = 'qg-contract-panel-cache-v1';

// ---------------------------------------------------------------------------
// Report export helpers
// ---------------------------------------------------------------------------
function buildMarkdownReport(filename, analysis) {
  const {
    riskScore = 0, riskLevel = '', summary = '',
    parties = [], governingLaw = '', jurisdiction = '',
    clauseAnalysis = [], missingClauses = [],
    criticalClauses = [], suggestions = [], faruiOpinion = null,
  } = analysis;

  const now = new Date().toLocaleString();
  const lines = [
    `# Contract Review Report`,
    ``,
    `**File:** ${filename}  `,
    `**Generated:** ${now}  `,
    `**Overall Risk:** ${riskLevel} (${riskScore}/100)`,
    ``,
    `---`,
    ``,
    `## Executive Summary`,
    ``,
    summary,
    ``,
    `---`,
    ``,
    `## Parties`,
    ``,
    ...parties.map((p) => `- **${p.role || 'Party'}** — ${p.name}${p.jurisdiction ? ` *(${p.jurisdiction})*` : ''}`),
    ``,
    `**Governing Law:** ${governingLaw}  `,
    `**Jurisdiction:** ${jurisdiction}`,
    ``,
    `---`,
    ``,
    `## Clause Analysis`,
    ``,
    `| Clause | Risk | Issue | Suggestion |`,
    `|--------|------|-------|------------|`,
    ...clauseAnalysis.map((c) =>
      `| ${c.clause} | **${c.risk}** | ${c.issue.replace(/\|/g, '\\|')} | ${c.suggestion.replace(/\|/g, '\\|')} |`
    ),
    ``,
    `---`,
    ``,
    `## Missing Clauses`,
    ``,
    missingClauses.length ? missingClauses.map((c) => `- ${c}`).join('\n') : '_None identified._',
    ``,
    `## Critical Clauses`,
    ``,
    criticalClauses.length ? criticalClauses.map((c) => `- ${c}`).join('\n') : '_None identified._',
    ``,
    `---`,
    ``,
    `## Recommendations`,
    ``,
    ...suggestions.map((s) => `**[${s.type}]** ${s.text}`),
  ];

  if (faruiOpinion) {
    lines.push(``, `---`, ``, `## AI Legal Opinion`, ``, faruiOpinion);
  }

  lines.push(``, `---`, ``, `*This report is generated by AI for reference only and does not constitute formal legal advice.*`);
  return lines.join('\n');
}

function downloadText(content, filename) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// Risk colour palette
// ---------------------------------------------------------------------------
const RISK_META = {
  LOW:      { cls: 'risk-low',      label: 'LOW',      hex: '#77d6c3' },
  MEDIUM:   { cls: 'risk-medium',   label: 'MEDIUM',   hex: '#f0bf68' },
  HIGH:     { cls: 'risk-high',     label: 'HIGH',     hex: '#ff8d7d' },
  CRITICAL: { cls: 'risk-critical', label: 'CRITICAL', hex: '#ff5555' },
};

function riskMeta(level) {
  return RISK_META[level] || RISK_META.MEDIUM;
}

// ---------------------------------------------------------------------------
// RiskBadge
// ---------------------------------------------------------------------------
function RiskBadge({ level, small = false }) {
  const meta = riskMeta(level);
  return (
    <span
      style={{
        display: 'inline-block',
        padding: small ? '3px 8px' : '5px 11px',
        borderRadius: '999px',
        border: `1px solid ${meta.hex}55`,
        background: `${meta.hex}18`,
        color: meta.hex,
        fontWeight: 700,
        fontSize: small ? '0.75rem' : '0.82rem',
        letterSpacing: '0.08em',
        textTransform: 'uppercase',
        whiteSpace: 'nowrap',
      }}
    >
      {meta.label}
    </span>
  );
}

// ---------------------------------------------------------------------------
// Reference platform links (static)
// ---------------------------------------------------------------------------
const PLATFORMS = [
  { name: 'Tongyi FaRui — Alibaba Legal AI', url: 'https://tongyi.aliyun.com/farui/home' },
  { name: 'Hetong Souso — Contract Intelligence', url: 'https://www.hetong.ai' },
  { name: 'Deli Legal Search', url: 'https://www.delilegal.com' },
  { name: 'Hairui Legal Intelligence', url: 'https://www.hairuizhifa.com' },
  { name: 'FaXingBao Legal Platform', url: 'https://www.faxingbao.cn' },
];

// ---------------------------------------------------------------------------
// ContractPanel
// ---------------------------------------------------------------------------
const ContractPanel = () => {
  const [file, setFile] = useState(null);
  const [fileChars, setFileChars] = useState(null);
  const [analysis, setAnalysis] = useState(null);
  const [status, setStatus] = useState('idle'); // idle|uploading|analyzing|success|error
  const [error, setError] = useState('');
  const [dragOver, setDragOver] = useState(false);
  const fileInputRef = useRef(null);
  const isMountedRef = useRef(true);

  useEffect(() => {
    isMountedRef.current = true;
    try {
      const raw = window.localStorage.getItem(CONTRACT_PANEL_CACHE_KEY);
      if (!raw) return;
      const cached = JSON.parse(raw);
      if (cached.fileName) {
        setFile({ name: cached.fileName });
      }
      setFileChars(cached.fileChars ?? null);
      setAnalysis(cached.analysis ?? null);
      setStatus(cached.status || 'idle');
      setError(cached.error || '');
    } catch {
      // ignore cache parse errors
    }
    return () => {
      isMountedRef.current = false;
    };
  }, []);

  useEffect(() => {
    const payload = {
      fileName: file?.name || '',
      fileChars,
      analysis,
      status,
      error,
    };
    try {
      window.localStorage.setItem(CONTRACT_PANEL_CACHE_KEY, JSON.stringify(payload));
    } catch {
      // ignore storage write errors
    }
  }, [analysis, error, file?.name, fileChars, status]);

  // ── File selection ────────────────────────────────────────────────────────
  const selectFile = useCallback((selected) => {
    if (!selected) return;
    setFile(selected);
    setAnalysis(null);
    setFileChars(null);
    setError('');
    setStatus('idle');
  }, []);

  const handleInputChange = (e) => selectFile(e.target.files?.[0]);

  const handleDragOver = (e) => { e.preventDefault(); setDragOver(true); };
  const handleDragLeave = ()  => setDragOver(false);
  const handleDrop = (e) => {
    e.preventDefault();
    setDragOver(false);
    selectFile(e.dataTransfer.files?.[0]);
  };

  // ── Upload + Analyze ──────────────────────────────────────────────────────
  const handleAnalyze = async () => {
    if (!file) return;
    setStatus('uploading');
    setError('');
    setAnalysis(null);

    try {
      // Step 1 — upload raw bytes, pass filename as query param
      const uploadRes = await fetch(
        `${API_BASE_URL}/contract/upload?filename=${encodeURIComponent(file.name)}`,
        { method: 'POST', body: file }
      );
      const uploadData = await uploadRes.json().catch(() => ({}));
      if (!uploadRes.ok) {
        throw new Error(uploadData.error || `Upload failed (HTTP ${uploadRes.status})`);
      }
      const { file_id, chars } = uploadData;
      if (!file_id) throw new Error('Server did not return a file_id.');
      if (isMountedRef.current) {
        setFileChars(chars);
      }

      // Step 2 — run analysis
      setStatus('analyzing');
      const analyzeRes = await fetch(`${API_BASE_URL}/contract/analyze`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ file_id }),
      });
      const analyzeData = await analyzeRes.json().catch(() => ({}));
      if (!analyzeRes.ok) {
        throw new Error(analyzeData.error || `Analysis failed (HTTP ${analyzeRes.status})`);
      }

      if (isMountedRef.current) {
        setAnalysis(analyzeData);
        setStatus('success');
      }
    } catch (err) {
      if (isMountedRef.current) {
        setError(err.message || 'Unknown error occurred.');
        setStatus('error');
      }
    }
  };

  // ── Helpers ───────────────────────────────────────────────────────────────
  const isWorking = status === 'uploading' || status === 'analyzing';

  const buttonLabel = {
    idle:      'Analyze Contract',
    uploading: 'Uploading…',
    analyzing: 'Analyzing with AI…',
    success:   '✅ Re-analyze',
    error:     'Retry',
  }[status] || 'Analyze Contract';

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <section className="panel">

      {/* Hero */}
      <div className="panel-hero">
        <div>
          <div className="panel-kicker">AI Contract Review</div>
          <h1>Contract Review</h1>
          <p>
            Upload a PDF or DOCX contract for a clause-by-clause risk analysis
            with Chinese law perspective and AI-generated opinions.
          </p>
        </div>
      </div>

      {/* Drop zone */}
      <div
        className={`upload-area${dragOver ? ' drag-over' : ''}`}
        onClick={() => fileInputRef.current?.click()}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
      >
        <div className="upload-icon">📄</div>
        <p className="upload-text">
          {file ? `📎 ${file.name}` : 'Click or drag & drop to upload a contract'}
        </p>
        <p className="upload-hint">Supports PDF and DOCX · Max 10 MB</p>
        <input
          ref={fileInputRef}
          type="file"
          accept=".pdf,.docx"
          onChange={handleInputChange}
          style={{ display: 'none' }}
        />
      </div>

      {/* Error banner */}
      {error && (
        <div className="info-banner danger" style={{ marginBottom: 16 }}>
          <strong>Error:</strong> {error}
        </div>
      )}

      {/* Analyze + Export buttons */}
      {file && (
        <div className="contract-action-row">
          <button
            className="primary-button"
            onClick={handleAnalyze}
            disabled={isWorking}
          >
            {buttonLabel}
          </button>
          {analysis && (
            <button
              className="secondary-button"
              onClick={() => {
                const reportName = file.name.replace(/\.[^.]+$/, '') + '_review_report.md';
                downloadText(buildMarkdownReport(file.name, analysis), reportName);
              }}
            >
              ⬇ Export Report
            </button>
          )}
          {fileChars && (
            <span className="contract-chars-note">
              {fileChars.toLocaleString()} chars extracted
            </span>
          )}
        </div>
      )}

      {/* Analysis results */}
      {analysis && <AnalysisResults analysis={analysis} />}

    </section>
  );
};

// ---------------------------------------------------------------------------
// AnalysisResults — all 9 sections
// ---------------------------------------------------------------------------
function AnalysisResults({ analysis }) {
  const {
    riskScore = 0,
    riskLevel = 'MEDIUM',
    summary = '',
    parties = [],
    governingLaw = 'Not specified',
    jurisdiction = 'Not specified',
    clauseAnalysis = [],
    missingClauses = [],
    criticalClauses = [],
    suggestions = [],
    faruiOpinion = null,
  } = analysis;

  const meta = riskMeta(riskLevel);

  return (
    <div style={{ display: 'grid', gap: 18, marginTop: 8 }}>

      {/* 1 — Risk Score Card */}
      <div className="answer-card">
        <div className="section-heading">
          <h2>Risk Assessment</h2>
          <RiskBadge level={riskLevel} />
        </div>
        <div className="risk-score-card">
          <div className="risk-score-left">
            <span className={`risk-score-number ${meta.cls}`}>{riskScore}</span>
            <span style={{ fontSize: '0.78rem', color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>/ 100</span>
            <div className="risk-bar-track" style={{ width: 72 }}>
              <div
                className={`risk-bar-fill ${meta.cls}`}
                style={{ width: `${riskScore}%` }}
              />
            </div>
          </div>
          <div className="risk-score-right">
            <p className="risk-summary-text">{summary}</p>
          </div>
        </div>
      </div>

      {/* 2 — Parties */}
      {parties.length > 0 && (
        <div className="answer-card">
          <div className="section-heading">
            <h2>Parties</h2>
          </div>
          <div className="parties-grid">
            {parties.map((p, i) => (
              <div key={i} className="party-card">
                <div className="party-role">{p.role || `Party ${i + 1}`}</div>
                <div className="party-name">{p.name}</div>
                {p.jurisdiction && (
                  <div className="party-jurisdiction">📍 {p.jurisdiction}</div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 3 — Governing law strip */}
      <div className="meta-strip">
        <span className="meta-pill">⚖️ Governing Law: <strong>{governingLaw}</strong></span>
        <span className="meta-pill">🏛️ Jurisdiction: <strong>{jurisdiction}</strong></span>
      </div>

      {/* 4 — Clause Analysis */}
      <div className="answer-card">
        <div className="section-heading">
          <h2>Clause Analysis</h2>
          <span className="section-chip">{clauseAnalysis.length} clauses reviewed</span>
        </div>
        {clauseAnalysis.length === 0 ? (
          <p style={{ color: 'var(--muted)', margin: 0 }}>No clause-level analysis was generated.</p>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table className="clause-table">
              <thead>
                <tr>
                  <th>Clause</th>
                  <th>Risk</th>
                  <th>Issue</th>
                  <th>Suggestion</th>
                </tr>
              </thead>
              <tbody>
                {clauseAnalysis.map((row, i) => (
                  <tr key={i}>
                    <td className="clause-name">{row.clause}</td>
                    <td><RiskBadge level={row.risk} small /></td>
                    <td>{row.issue}</td>
                    <td style={{ color: '#c8e6e0' }}>{row.suggestion}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* 5 — Missing Clauses */}
      {missingClauses.length > 0 && (
        <div className="answer-card">
          <div className="section-heading">
            <h2>Missing Clauses</h2>
            <span className="section-chip" style={{ color: '#f0bf68', borderColor: 'rgba(240,191,104,0.3)', background: 'rgba(240,191,104,0.08)' }}>
              {missingClauses.length} missing
            </span>
          </div>
          <div className="tag-row">
            {missingClauses.map((c, i) => (
              <span key={i} className="reference-tag">{c}</span>
            ))}
          </div>
        </div>
      )}

      {/* 6 — Critical Clauses */}
      {criticalClauses.length > 0 && (
        <div className="answer-card">
          <div className="section-heading">
            <h2>Critical Clauses</h2>
            <span className="section-chip" style={{ color: '#ff8d7d', borderColor: 'rgba(255,141,125,0.3)', background: 'rgba(255,141,125,0.08)' }}>
              Requires immediate attention
            </span>
          </div>
          <div className="tag-row">
            {criticalClauses.map((c, i) => (
              <span key={i} className="tag-pill">{c}</span>
            ))}
          </div>
        </div>
      )}

      {/* 7 — Suggestions */}
      {suggestions.length > 0 && (
        <div className="answer-card">
          <div className="section-heading">
            <h2>Recommendations</h2>
            <span className="section-chip">{suggestions.length} items</span>
          </div>
          {suggestions.map((s, i) => (
            <div key={i} className="suggestion-row">
              <RiskBadge level={s.type} small />
              <p className="suggestion-text">{s.text}</p>
            </div>
          ))}
        </div>
      )}

      {/* 8 — AI Legal Opinion */}
      {faruiOpinion && (
        <div className="answer-card">
          <div className="section-heading">
            <h2>AI Legal Opinion</h2>
          </div>
          <div className="answer-markdown">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {faruiOpinion}
            </ReactMarkdown>
          </div>
        </div>
      )}

      {/* 9 — Further Research Resources */}
      <div className="answer-card answer-card subtle">
        <div className="section-heading">
          <h2>Further Research</h2>
          <span className="section-chip">Legal AI Platforms</span>
        </div>
        <p style={{ margin: '0 0 14px', color: 'var(--muted-strong)', fontSize: '0.9rem' }}>
          For deeper research, consult these specialized legal platforms:
        </p>
        <div className="reference-platform-row">
          {PLATFORMS.map((p) => (
            <a
              key={p.name}
              href={p.url}
              target="_blank"
              rel="noopener noreferrer"
              className="platform-link"
            >
              🔗 {p.name}
            </a>
          ))}
        </div>
      </div>

    </div>
  );
}

export default ContractPanel;
